// <auto-generated />
namespace HrSmart.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class dfaq3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dfaq3));
        
        string IMigrationMetadata.Id
        {
            get { return "201502241050231_dfaq3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
